# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x, 15.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build --if-present

            - name: Run linters
              uses: wearerequired/lint-action@v1
              with:
                  eslint: true

            - name: Run tests
              run: npm test

            - name: Run code coverage
              run: npm run nyc

            - name: Run NYC Coverage Report
              uses: Tintef/nyc-reporter-action@0.1.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPORTER: "text" # defaults to 'text-summary'
                  COVERAGE_FOLDER: ".nyc_output"

            - name: Run SonarCloud scan
              uses: sonarsource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
